config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  resources :users
  resources :projects do
	  resources :tasks do
	  	member do
	  		get 'change_task_status'
	  	end
	  end
	end
end

app/models/admin.rb
class Admin < User
	has_many :projects, foreign_key: :user_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
	belongs_to :developer, foreign_key: :user_id
	belongs_to :project
end

app/models/developer.rb
class Developer < User
	has_many :assignments, foreign_key: :user_id
	has_many :projects, through: :assignments
	has_many :tasks, foreign_key: :user_id
end

app/models/project.rb
class Project < ApplicationRecord
	
	validates :name, presence: true

	belongs_to :admin, foreign_key: :user_id
	has_many :assignments
	has_many :developers, through: :assignments
	has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable

  validates_uniqueness_of :email
  validates :email, :name, :type, presence: true

  def admin?
  	type == "Admin"
  end

  def developer?
  	type == "Developer"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@projects = Project.all.includes(:tasks) if params[:activity_for] == "Project"
		@developers = Developer.all.includes(:tasks) if params[:activity_for] == "Developer"
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_developers, on: [:new, :edit]

	def index
		@projects = current_user.projects.includes(:tasks)
	end

	def new
		@project = Project.new
	end

	def edit
		@project = Project.find_by id: params[:id]
	end

	def create
		@project = current_user.projects.build name: project_params[:name]
		if @project.save!
			@project.assign_attributes name: '', developer_ids: project_params[:developers][:ids]
			flash[:notice] = "Project created sucessfully"
			redirect_to projects_path
		else
			flash[:error] = "Project not created"
			render action: :new
		end
	end

	def update
		@project = Project.find_by id: params[:id]
		@project.name = project_params[:name]
		if @project.save!
			@project.assign_attributes name: '', developer_ids: project_params[:developers][:ids]
			flash[:notice] = "Project updated sucessfully"
			redirect_to projects_path
		else
			flash[:error] = "Project not updated"
			render action: :edit
		end
	end

	private

	def project_params
		params.require(:project).permit :name, { developers: { ids: [] } }
	end

	def find_developers
		@developers = Developer.all
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :find_project

	def index
		@tasks = @project.tasks
		@tasks = @project.tasks.where(user_id: current_user.id) if current_user.developer?
	end

	def new
		@task = Task.new
	end

	def edit
		@task = Task.find_by id: params[:id]
	end

	def create
		@task = @project.tasks.new name: task_params[:name], status: "New", user_id: task_params[:user_id]
		if @task.save!
			flash[:notice] = "task created sucessfully"
			redirect_to project_tasks_path(@project)
		else
			flash[:error] = "task not created"
			render action: :new
		end
	end

	def update
		@task = Task.find_by id: params[:id]
		@task.name = task_params[:name]
		@task.user_id = task_params[:user_id]
		if @task.save!
			flash[:notice] = "task created sucessfully"
			redirect_to project_tasks_path(@project)
		else
			flash[:error] = "task not created"
			render action: :edit
		end
	end

	def change_task_status
		@task = Task.find_by id: params[:id]
		@task.user_id = current_user.id if params[:status] == "In Progress"
		@task.user_id = nil if params[:status] == "New"
		@task.status = params[:status]
		if @task.save
			flash[:notice] = "Task updated...."
		else
			flash[:error] = "Some error occured..."
		end
		redirect_to project_tasks_path(@project)
	end

	private

	def task_params
		params.require(:task).permit(:name, :user_id)
	end

	def find_project
		@project = Project.find_by id: params[:project_id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	
	def user_dashboard
		if current_user.admin?
			"admin"
		else
			"developer"
		end
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	def action_links(task)
		html = []
		if current_user.admin?
			html << link_to('Edit', edit_project_task_path(id: task.id)).to_s
		else
			if task.status == 'Done'
				html << "<span style='color:blue;'>Completed</span>"
			else
				html << link_to('In Progress', change_task_status_project_task_path(id: task.id, status: 'In Progress'))
				html << link_to('Done', change_task_status_project_task_path(id: task.id, status: 'Done'))
			end
		end
		html.join(" ").html_safe
	end
end

app/views/dashboard/_admin.html.erb
<h1><%= current_user.name %></h1>

<%= link_to "Developer Activities", root_path(activity_for: "Developer") %>
<%= link_to "Project Activities", root_path(activity_for: "Project") %>
<br/><br/>
<% if @projects.present? || @developers.present? %>
	<% objects = @projects || @developers %>
	<table border="1">
		<th>
			Status
		</th>
		<% objects.each do |object| %>
			<th><%= object.name %></th>
		<% end %>
		<tbody>
			<% ["Done", "In Progress", "New"].each do |status| %>
				<tr>
					<td>
						<%= status %>
					</td>
					<% objects.each do |object| %>
						<td>
							<% object.tasks.select { |task| task.status == status }.each do |task| %>
								<%= task.name %><br/>
							<% end %>
						</td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/dashboard/_developer.html.erb
<h1><%= current_user.name %></h1>

app/views/dashboard/index.html.erb
<%= render partial: user_dashboard %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="header">
        <span><%= link_to "Home", root_path %></span>
        <span><%= link_to "Projects", projects_path %></span>
        <span><%= link_to "Logout", destroy_user_session_path, :method => :delete %></span>
      </div>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<div>
	<span>Project Name:</span>
	<span><%= f.text_field :name, required: true %></span>
</div>
<div>
	<div>Assign Developers:</div>
	<% @developers.each do |developer| %>
		<div>
			<span>
				<!-- <input type=checkbox name="project[developer_ids][]" value="<%= developer.id %>"> -->
				<%= check_box_tag "project[developers][ids][]", developer.id, @project.developers.include?(developer) %>
			</span>
			<span>
				<%= developer.name %>
			</span>
		</div>
	<% end %>
</div>
<%= f.submit %>
<%= link_to "cancel", projects_path %>

app/views/projects/_projects.html.erb
<% if @projects.present? %>
	<% @projects.each do |project| %>
		<ul>
			<li>
				<%= project.name %>
				<% if current_user.admin? %>
					<%= link_to "Edit", edit_project_path(project.id) %>
				<% end %>
				<%= link_to "tasks", project_tasks_path(project.id) %>
			</li>
		</ul>
	<% end %>
<% end %>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
	<%= render partial: "form", locals: {f: f} %>
<% end%>

app/views/projects/index.html.erb
<% if current_user.admin? %>
	<%= link_to "Create Project", new_project_path %>
<% end %>
<%= render partial: "projects" %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
	<%= render partial: "form", locals: {f: f} %>
<% end%>

app/views/tasks/_form.html.erb
<div>
	<span>Task Name:</span>
	<span><%= f.text_field :name, required: true %></span>
</div>
<% if @project.developers.present? %>
	<div>
		<div>Assign Developers:</div>
		<% @project.developers.each do |developer| %>
			<div>
					<!-- <input type=checkbox name="project[developer_ids][]" value="<%= developer.id %>"> -->
				<%= radio_button_tag "task[user_id]", developer.id, @task.user_id == developer.id %>
				<%= developer.name %>
			</div>
		<% end %>
	</div>
<% end %>
<%= f.submit %>
<%= link_to "cancel", project_tasks_path %>

app/views/tasks/_tasks.html.erb
<% if @tasks.present? %>
	<% @tasks.each do |task| %>
		<ul>
			<li>
				<%= task.name %>
				<%= action_links(task) %>
			</li>
		</ul>
	<% end %>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for [@project, @task] do |f| %>
	<%= render partial: "form", locals: {f: f} %>
<% end%>

app/views/tasks/index.html.erb
<% if current_user.admin? %>
	<%= link_to "Create task", new_project_task_path %>
<% end %>
<%= render partial: "tasks" %>

<% if current_user.admin? %>
	<div id="piechart" style="width: 900px; height: 500px;"></div>
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = google.visualization.arrayToDataTable([
        ['Task status', 'status count'],
        ['Done', <%= @tasks.select { |task| task.status == "Done" }.size %>],
        ['New', <%= @tasks.select { |task| task.status == "New" }.size %>],
        ['In Progress', <%= @tasks.select { |task| task.status == "In Progress" }.size %>]
      ]);

      var options = {
        title: 'Task status'
      };

      var chart = new google.visualization.PieChart(document.getElementById('piechart'));

      chart.draw(data, options);
    }
  </script>
<% end %>

app/views/tasks/new.html.erb
<%= form_for [@project, @task] do |f| %>
	<%= render partial: "form", locals: {f: f} %>
<% end%>